### ISSUE TITLE
Continuous task names that are too long extend past the edge of the page to the right in the task view

### ISSUE THREAD

**Issue by nrcebarsalou** [NationalResearchCorporation/ScrumThing#14]
Task names that contain a single word that is very long with no spaces, will not automatically wrap the word and the word will extend to the right past the modal it is contained within.

Repro Steps:
Create a task with a description that contains a very long single word. (example: ThisnameisverylonglongerthananyothernamesitisthelongestLOOOOOOOOOOOONNNNNNNGGGGGGGGGGG)
Go to the View page and click on the task.
Observe the task name at the top of the modal.

Result: The name extends outside the screen to the right.
Expected: The name wraps and does not extend outside of it's boundaries.

**Comment by nrcjrichards** [comment]
Resolved with commit eea0b4ac8ac7cfd8a7e88c30516e54d1d94ad2af.
