### ISSUE TITLE
Hover Bubbles "Burned/Remaining" Stay on screen forever if you move/click your mouse just right

### ISSUE THREAD

**Issue by nrcebarsalou** [NationalResearchCorporation/ScrumThing#19]
Repro Steps:
Click and hold on a task with your mouse not over the Dev or QS hour displays.
With your mouse click still held down, move the mouse over the Dev or QS hour displays.
Wait for the "Burned/Remaining" test bubble to appear.
With your mouse click still held down move the task into another column and drop it.

Result:
The "Burned/Remaining" text bubble remains forever.

Expected:
The "Burned/Remaining" text bubble disappears when you aren't hovering over the Dev or QS hour displays.

**Comment by nrcjrichards** [comment]
Fixed with commit 3b18dbabb36893dee0509e7dd553905dfafdd5ad.
